dist: trusty
language: ruby


sudo: required
services:
  - docker


script: |
  .travis.d/build.sh &&
  cd .travis.d &&
  bundle install --gemfile=Gemfile --path vendor/bundle &&
  BUNDLE_GEMFILE=Gemfile bundle exec ruby pr_autodeploy.rb

env:
  global:
    - HACKGPROJECT_REV="52666d1e1d1eb7924f50a4f4c03201a2803b13ac"

    - DOCKER_ID_USER="hackgt"

