git:
    remote: https://github.com/HackGT/buzzer.git
    branch: master

secrets:
    - ADMIN_KEY_SECRET

    - SLACK_TOKEN
    - SLACK_WEBHOOK_URL

    - TWITTER_CONSUMER_KEY
    - TWITTER_CONSUMER_SECRET
    - TWITTER_HACKGT_ACCESS_TOKEN
    - TWITTER_HACKGT_ACCESS_TOKEN_SECRET

    - ONESIGNAL_APP_ID
    - ONESIGNAL_API_KEY
    
    - TWILIO_SID
    - TWILIO_TOKEN
    - TWILIO_SERVICE_SID
    - REGISTRATION_KEY
    - REGISTRATION_GRAPHQL

env:
    ONESIGNAL_DEFAULT_TITLE: HackGT Alert!

target_port: 8000
